networks:
  monitoring:
    name: monitoring
  workloads:
    name: workloads

services:
  api-server:
    container_name: api-server
    build:
      context: backend
      dockerfile: ../backend.Dockerfile
    environment:
      - ENDPOINT=otel-collector:4317
    restart: always
    networks:
      - monitoring
      - workloads
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: 'http://loki:3100/api/prom/push'